baseURL = 'https://blog.tessio.cc'
languageCode = 'en-us'
title = "tessio's links"
theme = 'typo'

[taxonomies]
tag = 'tags'


[params]
description = "A Tech Blog"
showFooter = false
theme = 'light'
colorPalette = 'eink'
hideHeader = false

# homeIntroTitle = 'Hi!'
homeIntroContent = """
This is the list of links to my person projects
1. Grafana dashboards:
    - [Ecoflow dashboard](https://dashboard.tessio.cc/d/KGnlUEp4s/ecoflow-prometheus?orgId=1&refresh=30s)
    - [Tapo smart plugs dashboard](https://dashboard.tessio.cc/d/c40p3MV4z/energy-monitoring?orgId=1&refresh=30s)
2. Github repositores:
    - [go-ecoflow-exporter](https://github.com/tess1o/go-ecoflow-exporter)
    - [go-ecoflow](https://github.com/tess1o/go-ecoflow)
"""

# Collection to display on home
#homeCollectionTitle = 'Posts'
#homeCollection = 'posts'

paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

[markup]
[markup.highlight]
style = 'algol'

